language: go

go:
  - 1.2

install:
  - go get github.com/laher/goxc
  - export PATH=$PATH:/home/travis/gopath/bin
  - go get -v ./...

script:
  - go build
  - goxc -pv=0.1.$TRAVIS_BUILD_NUMBER

deploy:
  provider: s3
  bucket: "rmq"
  skip_cleanup: true
  secret_access_key:
    secure: Pox9zyDP9t65iEOM6DfFasGhshwlxEdiszn9NXYZadFsI/aSChAit8KSq7qhZ5LMxqDhV5mo7HVSaXHbUEVCipvr0MAKBzVSCPL0bjrAYBpccP4Ba4wOtaQGih/1riH8+YmcB8l0UtGSrLVaBTCqhc584NvfrvupGmLFla8NnL8=
  access_key_id:
    secure: Tv7d9drf7UL81wU/m+aPgZQLQ/CLZPCGYNyy8zHRBPpAiuU4olTztdZ9Kksavnp9qLa5ct1gLkOcAFQZfygf8tq+CUeJ/menvQhJ5pmLhKXgVfzBRJH7sE1KTaZDTIzqmqqP4XaS8Puc9jg7qzgypZG780cbXaJfbiCA8LRPxVA=
